###############################
#                             #
#            Config           #
#                             #
###############################
token: ""
command: "true"
commandWord: "!raid"
channels: "true"
channelName: "nut-bot"
atEveryone: "true"
customAt: "false"
customAtID: ""

